### PR TITLE
Add github actions back

### PR DESCRIPTION
**Pull request by alf1e**
Add github actions and builds back

### CODE REVIEW

**Review by m31-galaxy — CHANGES_REQUESTED** [review]
I have no idea how to merge only some files, so I'm just gonna request for you to split the modified `docker-compose.yml` into its own file (e.g. `docker-compose-online.yml`). Once that's been done, I'll merge you in 🙌

**Comment by alf1e** [comment]
Wait I need to re-add old compose

**Comment by alf1e** [comment]
Done

**Comment by m31-galaxy** [comment]
You could've also dropped the commit I think, but that probably works as well

**Review by m31-galaxy — APPROVED** [review]
I'll make a couple cosmetic tweaks, but other than that, looks good!

**Comment by alf1e** [comment]
> I'll make a couple cosmetic tweaks, but other than that, looks good!

Great!

**Pull request merged**
